# Output File
AVAILABLE_OUTPUT_FILE_EXTENSIONS = 'png', 'pdf'
DEFAULT_OUTPUT_FILE_EXTENSION = AVAILABLE_OUTPUT_FILE_EXTENSIONS[0]

# Template
INPUT_FIELD_LAYER_KINDS = ['type', 'pixel']
TEMPLATE_KEY_NAME = 'name'
TEMPLATE_KEY_PSD_FILE = 'psd_file'
TEMPLATE_KEY_PSD_COLOR_MODE = 'color_mode'
TEMPLATE_KEY_IMAGE_SIZE = 'image_size'
TEMPLATE_KEY_INPUT_FIELDS = 'input_fields'
TEMPLATE_KEY_INPUT_FIELD_LAYER_ID = 'layer_id'
TEMPLATE_KEY_INPUT_FIELD_TYPE = 'type'
TEMPLATE_KEY_INPUT_FIELD_VALUE = 'value'
TEMPLATE_KEY_INPUT_FIELD_POSITION = 'position'
TEMPLATE_KEY_INPUT_FIELD_SIZE = 'size'

# Template Value
TEMPLATE_REPLACE_PATTERN = r'\{\{([^\{\}]*)\}\}'
